# Global configuration
global:
  checkNewVersion: true
  sendAnonymousUsage: false

# API and dashboard configuration
api:
  dashboard: true
  insecure: false

# Entry points configuration
entryPoints:
  web:
    address: ":80"
    # Redirect HTTP to HTTPS
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https
  websecure:
    address: ":443"

# SSL configuration with Let's Encrypt
certificatesResolvers:
  cloudflare:
    acme:
      email: "jp.de.jong@icloud.com"
      storage: /acme.json
      dnsChallenge:
        provider: cloudflare
        resolvers:
          - "1.1.1.1:53"
          - "1.0.0.1:53"

# Provider configuration
providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false
    network: traefik_proxy